var myArray = [
    {"rank":"63","country":"India","gold":"0","silver":"1","bronze":"1","total":"2"},
{"rank":"1","country":"China","gold":"32","silver":"20","bronze":"16","total":"68"},
{"rank":"2","country":"United States","gold":"22","silver":"27","bronze":"19","total":"68"},
{"rank":"3","country":"Japan","gold":"18","silver":"6","bronze":"10","total":"34"},
{"rank":"4","country":"Australia","gold":"14","silver":"4","bronze":"15","total":"33"},
{"rank":"5","country":"Great Britain","gold":"13","silver":"15","bronze":"13","total":"41"},
{"rank":"6","country":"ROC","gold":"12","silver":"21","bronze":"18","total":"51"},
{"rank":"7","country":"Germany","gold":"8","silver":"8","bronze":"14","total":"30"},
{"rank":"8","country":"France","gold":"6","silver":"10","bronze":"8","total":"24"},
{"rank":"9","country":"Netherlands","gold":"6","silver":"7","bronze":"7","total":"20"},
{"rank":"10","country":"Republic of Korea","gold":"6","silver":"4","bronze":"9","total":"19"},
{"rank":"11","country":"New Zealand","gold":"6","silver":"4","bronze":"5","total":"15"},
{"rank":"12","country":"Italy","gold":"5","silver":"9","bronze":"15","total":"29"},
{"rank":"13","country":"Czech Republic","gold":"4","silver":"3","bronze":"1","total":"8"},
{"rank":"14","country":"Canada","gold":"3","silver":"4","bronze":"7","total":"14"},
{"rank":"15","country":"Switzerland","gold":"3","silver":"4","bronze":"5","total":"12"},
{"rank":"16","country":"Hungary","gold":"3","silver":"4","bronze":"3","total":"10"},
{"rank":"17","country":"Brazil","gold":"3","silver":"3","bronze":"6","total":"12"},
{"rank":"18","country":"Cuba","gold":"3","silver":"3","bronze":"3","total":"9"},
{"rank":"19","country":"Croatia","gold":"3","silver":"2","bronze":"2","total":"7"},
{"rank":"20","country":"Chinese Taipei","gold":"2","silver":"4","bronze":"4","total":"10"},
{"rank":"21","country":"Denmark","gold":"2","silver":"1","bronze":"3","total":"6"},
{"rank":"22","country":"Norway","gold":"2","silver":"1","bronze":"1","total":"4"},
{"rank":"22","country":"Slovenia","gold":"2","silver":"1","bronze":"1","total":"4"},
{"rank":"24","country":"Ecuador","gold":"2","silver":"1","bronze":"0","total":"3"},
{"rank":"25","country":"Greece","gold":"2","silver":"0","bronze":"1","total":"3"},
{"rank":"26","country":"Kosovo","gold":"2","silver":"0","bronze":"0","total":"2"},
{"rank":"26","country":"Qatar","gold":"2","silver":"0","bronze":"0","total":"2"},
{"rank":"28","country":"Spain","gold":"1","silver":"4","bronze":"4","total":"9"},
{"rank":"29","country":"Georgia","gold":"1","silver":"4","bronze":"1","total":"6"},
{"rank":"30","country":"Romania","gold":"1","silver":"3","bronze":"0","total":"4"},
{"rank":"30","country":"Sweden","gold":"1","silver":"3","bronze":"0","total":"4"},
{"rank":"30","country":"Venezuela","gold":"1","silver":"3","bronze":"0","total":"4"},
{"rank":"33","country":"Hong Kong","gold":"1","silver":"2","bronze":"0","total":"3"},
{"rank":"33","country":"Poland","gold":"1","silver":"2","bronze":"0","total":"3"},
{"rank":"33","country":"Slovakia","gold":"1","silver":"2","bronze":"0","total":"3"},
{"rank":"33","country":"South Africa","gold":"1","silver":"2","bronze":"0","total":"3"},
{"rank":"37","country":"Austria","gold":"1","silver":"1","bronze":"3","total":"5"},
{"rank":"37","country":"Indonesia","gold":"1","silver":"1","bronze":"3","total":"5"},
{"rank":"37","country":"Serbia","gold":"1","silver":"1","bronze":"3","total":"5"},
{"rank":"40","country":"Jamaica","gold":"1","silver":"1","bronze":"2","total":"4"},
{"rank":"41","country":"Belgium","gold":"1","silver":"1","bronze":"1","total":"3"},
{"rank":"41","country":"Ethiopia","gold":"1","silver":"1","bronze":"1","total":"3"},
{"rank":"43","country":"Philippines","gold":"1","silver":"1","bronze":"0","total":"2"},
{"rank":"43","country":"Tunisia","gold":"1","silver":"1","bronze":"0","total":"2"},
{"rank":"45","country":"Turkey","gold":"1","silver":"0","bronze":"5","total":"6"},
{"rank":"46","country":"Ireland","gold":"1","silver":"0","bronze":"2","total":"3"},
{"rank":"46","country":"Israel","gold":"1","silver":"0","bronze":"2","total":"3"},
{"rank":"48","country":"Belarus","gold":"1","silver":"0","bronze":"1","total":"2"},
{"rank":"48","country":"Estonia","gold":"1","silver":"0","bronze":"1","total":"2"},
{"rank":"48","country":"Fiji","gold":"1","silver":"0","bronze":"1","total":"2"},
{"rank":"48","country":"Uzbekistan","gold":"1","silver":"0","bronze":"1","total":"2"},
{"rank":"52","country":"Bermuda","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"52","country":"Iran","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"52","country":"Latvia","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"52","country":"Morocco","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"52","country":"Puerto Rico","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"52","country":"Thailand","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"58","country":"Colombia","gold":"0","silver":"2","bronze":"1","total":"3"},
{"rank":"58","country":"Dominican Republic","gold":"0","silver":"2","bronze":"1","total":"3"},
{"rank":"58","country":"Portugal","gold":"0","silver":"2","bronze":"1","total":"3"},
{"rank":"61","country":"Ukraine","gold":"0","silver":"1","bronze":"5","total":"6"},
{"rank":"62","country":"Mongolia","gold":"0","silver":"1","bronze":"2","total":"3"},
{"rank":"63","country":"Kenya","gold":"0","silver":"1","bronze":"1","total":"2"},
{"rank":"63","country":"San Marino","gold":"0","silver":"1","bronze":"1","total":"2"},
{"rank":"63","country":"Uganda","gold":"0","silver":"1","bronze":"1","total":"2"},
{"rank":"67","country":"Bulgaria","gold":"0","silver":"1","bronze":"0","total":"1"},
{"rank":"67","country":"Jordan","gold":"0","silver":"1","bronze":"0","total":"1"},
{"rank":"67","country":"North Macedonia","gold":"0","silver":"1","bronze":"0","total":"1"},
{"rank":"67","country":"Turkmenistan","gold":"0","silver":"1","bronze":"0","total":"1"},
{"rank":"71","country":"Kazakhstan","gold":"0","silver":"0","bronze":"3","total":"3"},
{"rank":"71","country":"Mexico","gold":"0","silver":"0","bronze":"3","total":"3"},
{"rank":"73","country":"Azerbaijan","gold":"0","silver":"0","bronze":"2","total":"2"},
{"rank":"73","country":"Egypt","gold":"0","silver":"0","bronze":"2","total":"2"},
{"rank":"75","country":"Argentina","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"75","country":"Armenia","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"75","country":"Cote d'Ivoire","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"75","country":"Finland","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"75","country":"Ghana","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"75","country":"Kuwait","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"75","country":"Malaysia","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"75","country":"Nigeria","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"83","country":"Afghanistan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Albania","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Algeria","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"American Samoa","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Andorra","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Angola","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Antigua and Barbuda","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Aruba","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Bahamas","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Bahrain","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Bangladesh","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Barbados","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Belize","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Benin","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Bhutan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Bolivia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Bosnia and Herzegovina","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Botswana","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"British Virgin Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Brunei Darussalam","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Burkina Faso","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Burundi","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Cambodia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Cameroon","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Cape Verde","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Cayman Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Central African Republic","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Chad","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Chile","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Comoros","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Congo","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Cook Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Costa Rica","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Cyprus","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Djibouti","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Dominica","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"DR Congo","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"El Salvador","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Equatorial Guinea","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Eritrea","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Eswatini","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Federated States of Micronesia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Gabon","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Gambia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Grenada","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Guam","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Guatemala","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Guinea","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Guinea-Bissau","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Guyana","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Haiti","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Honduras","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Iceland","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Iraq","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Kiribati","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Kyrgyzstan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Laos","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Lebanon","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Lesotho","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Liberia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Libya","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Liechtenstein","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Lithuania","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Luxembourg","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Madagascar","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Malawi","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Maldives","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Mali","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Malta","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Marshall Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Mauritania","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Mauritius","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Moldova","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Monaco","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Montenegro","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Mozambique","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Myanmar","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Namibia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Nauru","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Nepal","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Nicaragua","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Niger","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Oman","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Pakistan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Palau","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Palestine","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Panama","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Papua New Guinea","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Paraguay","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Peru","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Refugee Olympic Team","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Rwanda","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Saint Kitts and Nevis","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Saint Lucia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Samoa","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Sao Tome and Principe","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Saudi Arabia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Senegal","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Seychelles","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Sierra Leone","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Singapore","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Solomon Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Somalia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"South Sudan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Sri Lanka","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"St Vincent and the Grenadines","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Sudan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Suriname","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Syria","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Tajikistan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Tanzania","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Timor-Leste","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Togo","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Tonga","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Trinidad and Tobago","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Tuvalu","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"United Arab Emirates","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Uruguay","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Vanuatu","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Vietnam","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Virgin Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Yemen","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Zambia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"83","country":"Zimbabwe","gold":"0","silver":"0","bronze":"0","total":"0"}
]

buildTable(myArray)



function buildTable(data){
    var table = document.getElementById('myTable')

    for (var i = 0; i < data.length; i++){
        var row = `<tr>
                        <td>${data[i].rank}</td>
                        <td>${data[i].country}</td>
                        <td>${data[i].gold}</td>
                        <td>${data[i].silver}</td>
                        <td>${data[i].bronze}</td>
                        <td>${data[i].total}</td>
                  </tr>`
        table.innerHTML += row


    }
}
