var myArray = [
    {"rank":"59","country":"India","gold":"0","silver":"1","bronze":"1","total":"2"},
{"rank":"1","country":"China","gold":"24","silver":"14","bronze":"13","total":"51"},
{"rank":"2","country":"United States","gold":"20","silver":"23","bronze":"16","total":"59"},
{"rank":"3","country":"Japan","gold":"17","silver":"5","bronze":"9","total":"31"},
{"rank":"4","country":"Australia","gold":"14","silver":"3","bronze":"14","total":"31"},
{"rank":"5","country":"ROC","gold":"12","silver":"19","bronze":"13","total":"44"},
{"rank":"6","country":"Great Britain","gold":"10","silver":"10","bronze":"12","total":"32"},
{"rank":"7","country":"France","gold":"5","silver":"10","bronze":"6","total":"21"},
{"rank":"8","country":"Republic of Korea","gold":"5","silver":"4","bronze":"8","total":"17"},
{"rank":"9","country":"Italy","gold":"4","silver":"8","bronze":"15","total":"27"},
{"rank":"10","country":"Netherlands","gold":"4","silver":"7","bronze":"6","total":"17"},
{"rank":"11","country":"Germany","gold":"4","silver":"4","bronze":"11","total":"19"},
{"rank":"12","country":"New Zealand","gold":"4","silver":"3","bronze":"4","total":"11"},
{"rank":"13","country":"Czech Republic","gold":"4","silver":"3","bronze":"1","total":"8"},
{"rank":"14","country":"Canada","gold":"3","silver":"4","bronze":"7","total":"14"},
{"rank":"15","country":"Switzerland","gold":"3","silver":"4","bronze":"5","total":"12"},
{"rank":"16","country":"Croatia","gold":"3","silver":"2","bronze":"2","total":"7"},
{"rank":"17","country":"Chinese Taipei","gold":"2","silver":"4","bronze":"4","total":"10"},
{"rank":"18","country":"Brazil","gold":"2","silver":"3","bronze":"5","total":"10"},
{"rank":"19","country":"Hungary","gold":"2","silver":"2","bronze":"2","total":"6"},
{"rank":"20","country":"Slovenia","gold":"2","silver":"1","bronze":"1","total":"4"},
{"rank":"21","country":"Ecuador","gold":"2","silver":"0","bronze":"0","total":"2"},
{"rank":"21","country":"Kosovo","gold":"2","silver":"0","bronze":"0","total":"2"},
{"rank":"21","country":"Qatar","gold":"2","silver":"0","bronze":"0","total":"2"},
{"rank":"24","country":"Spain","gold":"1","silver":"3","bronze":"3","total":"7"},
{"rank":"25","country":"Georgia","gold":"1","silver":"3","bronze":"1","total":"5"},
{"rank":"26","country":"Romania","gold":"1","silver":"3","bronze":"0","total":"4"},
{"rank":"26","country":"Sweden","gold":"1","silver":"3","bronze":"0","total":"4"},
{"rank":"26","country":"Venezuela","gold":"1","silver":"3","bronze":"0","total":"4"},
{"rank":"29","country":"Hong Kong","gold":"1","silver":"2","bronze":"0","total":"3"},
{"rank":"29","country":"Slovakia","gold":"1","silver":"2","bronze":"0","total":"3"},
{"rank":"29","country":"South Africa","gold":"1","silver":"2","bronze":"0","total":"3"},
{"rank":"32","country":"Austria","gold":"1","silver":"1","bronze":"3","total":"5"},
{"rank":"33","country":"Denmark","gold":"1","silver":"1","bronze":"2","total":"4"},
{"rank":"33","country":"Serbia","gold":"1","silver":"1","bronze":"2","total":"4"},
{"rank":"35","country":"Belgium","gold":"1","silver":"1","bronze":"1","total":"3"},
{"rank":"35","country":"Jamaica","gold":"1","silver":"1","bronze":"1","total":"3"},
{"rank":"35","country":"Norway","gold":"1","silver":"1","bronze":"1","total":"3"},
{"rank":"38","country":"Poland","gold":"1","silver":"1","bronze":"0","total":"2"},
{"rank":"38","country":"Tunisia","gold":"1","silver":"1","bronze":"0","total":"2"},
{"rank":"40","country":"Ireland","gold":"1","silver":"0","bronze":"2","total":"3"},
{"rank":"40","country":"Israel","gold":"1","silver":"0","bronze":"2","total":"3"},
{"rank":"40","country":"Turkey","gold":"1","silver":"0","bronze":"2","total":"3"},
{"rank":"43","country":"Belarus","gold":"1","silver":"0","bronze":"1","total":"2"},
{"rank":"43","country":"Estonia","gold":"1","silver":"0","bronze":"1","total":"2"},
{"rank":"43","country":"Fiji","gold":"1","silver":"0","bronze":"1","total":"2"},
{"rank":"43","country":"Uzbekistan","gold":"1","silver":"0","bronze":"1","total":"2"},
{"rank":"47","country":"Bermuda","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"47","country":"Ethiopia","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"47","country":"Greece","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"47","country":"Iran","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"47","country":"Latvia","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"47","country":"Philippines","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"47","country":"Thailand","gold":"1","silver":"0","bronze":"0","total":"1"},
{"rank":"54","country":"Colombia","gold":"0","silver":"2","bronze":"1","total":"3"},
{"rank":"55","country":"Dominican Republic","gold":"0","silver":"2","bronze":"0","total":"2"},
{"rank":"56","country":"Ukraine","gold":"0","silver":"1","bronze":"5","total":"6"},
{"rank":"57","country":"Indonesia","gold":"0","silver":"1","bronze":"2","total":"3"},
{"rank":"57","country":"Mongolia","gold":"0","silver":"1","bronze":"2","total":"3"},
{"rank":"59","country":"Cuba","gold":"0","silver":"1","bronze":"1","total":"2"},
{"rank":"59","country":"Portugal","gold":"0","silver":"1","bronze":"1","total":"2"},
{"rank":"59","country":"San Marino","gold":"0","silver":"1","bronze":"1","total":"2"},
{"rank":"59","country":"Uganda","gold":"0","silver":"1","bronze":"1","total":"2"},
{"rank":"64","country":"Bulgaria","gold":"0","silver":"1","bronze":"0","total":"1"},
{"rank":"64","country":"Jordan","gold":"0","silver":"1","bronze":"0","total":"1"},
{"rank":"64","country":"North Macedonia","gold":"0","silver":"1","bronze":"0","total":"1"},
{"rank":"64","country":"Turkmenistan","gold":"0","silver":"1","bronze":"0","total":"1"},
{"rank":"68","country":"Kazakhstan","gold":"0","silver":"0","bronze":"3","total":"3"},
{"rank":"68","country":"Mexico","gold":"0","silver":"0","bronze":"3","total":"3"},
{"rank":"70","country":"Azerbaijan","gold":"0","silver":"0","bronze":"2","total":"2"},
{"rank":"70","country":"Egypt","gold":"0","silver":"0","bronze":"2","total":"2"},
{"rank":"72","country":"Argentina","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"72","country":"Cote d'Ivoire","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"72","country":"Finland","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"72","country":"Kuwait","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"72","country":"Malaysia","gold":"0","silver":"0","bronze":"1","total":"1"},
{"rank":"77","country":"Afghanistan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Albania","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Algeria","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"American Samoa","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Andorra","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Angola","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Antigua and Barbuda","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Armenia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Aruba","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Bahamas","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Bahrain","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Bangladesh","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Barbados","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Belize","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Benin","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Bhutan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Bolivia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Bosnia and Herzegovina","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Botswana","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"British Virgin Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Brunei Darussalam","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Burkina Faso","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Burundi","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Cambodia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Cameroon","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Cape Verde","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Cayman Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Central African Republic","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Chad","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Chile","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Comoros","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Congo","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Cook Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Costa Rica","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Cyprus","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Djibouti","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Dominica","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"DR Congo","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"El Salvador","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Equatorial Guinea","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Eritrea","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Eswatini","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Federated States of Micronesia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Gabon","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Gambia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Ghana","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Grenada","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Guam","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Guatemala","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Guinea","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Guinea-Bissau","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Guyana","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Haiti","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Honduras","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Iceland","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Iraq","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Kenya","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Kiribati","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Kyrgyzstan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Laos","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Lebanon","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Lesotho","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Liberia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Libya","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Liechtenstein","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Lithuania","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Luxembourg","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Madagascar","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Malawi","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Maldives","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Mali","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Malta","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Marshall Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Mauritania","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Mauritius","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Moldova","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Monaco","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Montenegro","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Morocco","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Mozambique","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Myanmar","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Namibia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Nauru","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Nepal","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Nicaragua","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Niger","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Nigeria","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Oman","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Pakistan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Palau","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Palestine","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Panama","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Papua New Guinea","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Paraguay","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Peru","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Puerto Rico","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Refugee Olympic Team","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Rwanda","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Saint Kitts and Nevis","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Saint Lucia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Samoa","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Sao Tome and Principe","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Saudi Arabia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Senegal","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Seychelles","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Sierra Leone","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Singapore","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Solomon Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Somalia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"South Sudan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Sri Lanka","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"St Vincent and the Grenadines","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Sudan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Suriname","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Syria","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Tajikistan","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Tanzania","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Timor-Leste","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Togo","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Tonga","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Trinidad and Tobago","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Tuvalu","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"United Arab Emirates","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Uruguay","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Vanuatu","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Vietnam","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Virgin Islands","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Yemen","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Zambia","gold":"0","silver":"0","bronze":"0","total":"0"},
{"rank":"77","country":"Zimbabwe","gold":"0","silver":"0","bronze":"0","total":"0"}
]

buildTable(myArray)



function buildTable(data){
    var table = document.getElementById('myTable')

    for (var i = 0; i < data.length; i++){
        var row = `<tr>
                        <td>${data[i].rank}</td>
                        <td>${data[i].country}</td>
                        <td>${data[i].gold}</td>
                        <td>${data[i].silver}</td>
                        <td>${data[i].bronze}</td>
                        <td>${data[i].total}</td>
                  </tr>`
        table.innerHTML += row


    }
}